### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by Frankr05** [pivotal-cf/docs-operating-pas#116]
The v2.13 page of document titled "Deploying TAS for VMs with NSX-T Networking" contains broken links in the Prerequisites section. The broken links are titled "Deploying Ops Manager on vSphere" and "Configuring BOSH Director on vSphere."

![Screen Shot 2022-12-09 at 10 54 59 AM](https://user-images.githubusercontent.com/91903034/206777457-4477f84d-13a5-4bf3-84ba-9bfe18ab2a6f.png)

**Comment by anita-flegg** [comment]
Fixed in 2.13, 3.0, and master
