### ISSUE TITLE
proposal: remove or update `ActiveLocks` metric

### ISSUE THREAD

**Issue by LukeWinikates** [pivotal-cf/docs-operating-pas#117]
The Key Performance Indicators docs page encourages users to monitor the `ActiveLocks` metric from `locket`.

We've implemented an alert on this metric, but the desired number of locks varies based on the TAS version.

* tas 2.13: `5`
* tas 3:  `6` 

We can update the KPI doc to show that the threshold is version-specific, but I also think that the proposed actions for troubleshooting an unexpected number of locks are very broad. It looks like this KPI is indirectly monitoring the health of `bbs`, `Auctioneer`, `TPS Watcher`, `Routing API`, and `Clock Global`. But monitoring an aggregate of those means that when the TAS operator gets paged, they have to go fishing to see if any those components are having problems.

## proposal: delete this broad KPI and provide specific ones for each component that contributes to the desired lock number

For example, `bbs` already seems to be covered by its own `bbs.LockHeld` metric and a KPI to monitor that metric. so is Auctioneer. Should `LockHeld` metrics be monitored for the other 3 processes? Are there other metrics that would better identify if those processes are not healthy?

## thought: KPIs and user-impacting events
My team treats the KPIs as TAS' suggestions for alert criteria that should result in paging an operator in the middle of the night. For that reason, I want the KPIs to be one of two things:
1. a metric that shows an urgent user-affecting issue happening *right now*
2. a metric that predicts a user-affecting issue is about to happen

I think this KPI might almost be `2`, but the KPI doc doesn't call out the kinds of user-facing issues that might happen if the lock number is not the expected value.

## thought: version-dependent thresholds a code smell?
Tools for monitoring TAS have different release cycles than TAS itself; if we are monitoring granular internal metrics within TAS, it is difficult for monitoring tools to keep up as TAS internals change. Internal metrics can be useful for investigating and diagnosing an issue, but if their values vary from version to version, they become challenging to use for alerting.

## proposal: have the metric tell the desired value using a metric tag
If we *do* keep this KPI, the metric should be include a tag that says what the desired value should be, so that alerting tools don't need supplemental knowledge about the TAS version to alert on this metric.

e.g.:

metric looks like:
`ActiveLocks: 4 { source_id: locket, index: abcdef, desired_value: 5}`

alert psuedocode:
`ActiveLocks.value != ActiveLocks.desired_value`

current alert pseudocode has to be:
`AlertLocks.value != (tas.version < 3 ? 5 : 6)`

**Comment by ameowlia** [comment]
Hi @LukeWinikates,

Thank you for opening for such a thoughtful issue!

Context: I am an eng on the team that maintains locket and _some_ of the things that use it.

I agree with your thought process 💯 %. 
* version dependent KPIs is a smell
* individual `LockHeld` metrics make more sense than one `ActiveLocks` metric

Additional points against using one `ActiveLocks` metric:
* I didn't know this KPI existed! So when we made a new component that used locket we didn't know to update it. I am worried this would happen again in the future.
* The new component that uses locket -- I believe -- is the [policy-server-asg-syncer](https://github.com/cloudfoundry/cf-networking-release/tree/develop/jobs/policy-server-asg-syncer). However, this job is only started if a customer enables dynamic ASGs. So I suspect when this job is disabled that it does not claim a lock from locket. Which means that the KPI should be 5 or if you have dynamic ASGs enabled 6 (which I believe is turned on by default in TAS 3).

**Comment by LukeWinikates** [comment]
Thanks @ameowlia! I went ahead and created PR to remove the ActiveLocks KPI. Given that the value is uncertain and that we'd have to work pretty hard to make it accurate for TAS 3, I think removing it is the right move.

I'm not sure if there are stakeholders besides you and me who we need to satisfy 🙃

I'm also assuming for now *not* to add LockHeld KPIs for the other components. I'm not sure there's any evidence that these are 'key' indicators to measure and alert on. I *think* that monitoring the ActiveLocks from these components was a basically a form of heartbeat metric.

**Comment by ameowlia** [comment]
@LukeWinikates Sounds like a good plan. 

❓ Can you also PR release notes for TAS 3.0 indicating (maybe as a breaking change??) that with that version we no longer suggest using this KPI?
