### ISSUE TITLE
Formatting not displaying correctly

### ISSUE THREAD

**Issue by ctlong** [pivotal-cf/docs-operating-pas#125]
### Describe the bug

My pair and I noticed while scrolling through the [Configuring TAS for VMs page for TAS 3.0](https://docs.pivotal.io/application-service/3-0/operating/configure-pas.html) that many of the headers and other formatting below a certain point in the page do not appear to display correctly.

For example, the `Configure App Containers` header is displayed in raw Markdown style (i.e. `## Configure App Containers`) rather than as an h2 HTML tag.

### Reproduction steps

1. Visit the [Configuring TAS for VMs page for TAS 3.0](https://docs.pivotal.io/application-service/3-0/operating/configure-pas.html)
2. Scroll down to the `Configure App Containers` header and beyond
3. See that the formatting is all in raw Markdown form
...

### Expected behavior

We would expect that the raw Markdown would all be converted into nicely styled HTML based on VMware's style guide, as the rest of the website appears to be.

### Additional context

cc @rroberts2222

**Comment by anita-flegg** [comment]
This is caused by the migration to VMware docs and the fact that most of the sections on this page are in partials.
I noticed this problem, but when we checked it on Tuesday, it looked fine in TAS 3.0.
Have you done a hard refresh on the page?

**Comment by ctlong** [comment]
I just hard refreshed the page, and it still looks wonky unfortunately.

**Comment by anita-flegg** [comment]
OK -- I will go back into it. Thanks for letting me know.

**Comment by anita-flegg** [comment]
Just checked again and I am not seeing any problems on the page: https://docs.vmware.com/en/VMware-Tanzu-Application-Service/3.0/tas-for-vms/configure-pas.html

**Comment by ctlong** [comment]
Yes, it appears correctly for us now too! Not sure what fixed it, maybe just the page cache as you previously suggested.
