### ISSUE TITLE
Enhanced instructions for configuring NSX-T load balancer virtual servers

### ISSUE THREAD

**Issue by dbuchko** [pivotal-cf/docs-operating-pas#25]
Currently, the documentation for [configuring TAS for NSX-T](https://docs.pivotal.io/platform/application-service/2-9/operating/vsphere-nsx-t.html#nsx-t-load-balancer) provides a warning that _"Foundations requiring end-to-end encryption should not enable the virtual server on port 80, or, if enabled, should configure it to redirect traffic to the encrypted port (443)."_   Detailed NSX-T configuration instructions are provided for those customers who do _not_ require end-to-end encryption.  (The existing docs indicate to use a `Layer 4 (TCP)` **application type** and  the `nsx-default-lb-fast-tcp-profile` **application profile**.)  However there are no instructions on precisely how to configure the redirection in NSX-T for those customers who _do_ require end-to-end encryption.   Request that the docs be enhanced to cover this additional configuration.

**Comment by paigecalvert** [comment]
Thank you @dbuchko! We'll look into prioritizing this against our other work. I'm going to close out this issue, but feel free to keep an eye on the linked Tracker story or reach out to us in the #pcf-docs channel!
