### ISSUE TITLE
Optional reference In configure Networking

### ISSUE THREAD

**Issue by quixoticmonk** [pivotal-cf/docs-operating-pas#28]
- **Path** : https://docs.pivotal.io/platform/application-service/2-9/operating/configure-pas.html
- **Section**: Configure Networking
- **Wording** : (Optional) Under Balancing algorithm used by the Gorouter

The field referenced here is a radiobuttion and is selected by default with no obvious option to make this optional. The reference of this field being **Optional** should be omitted.

If confirmed, I can open a PR and update it.

**Comment by mlimonczenko** [comment]
Hello @quixoticmonk,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
