### ISSUE TITLE
Configure Networking - Service Mesh (Beta) - pane

### ISSUE THREAD

**Issue by quixoticmonk** [pivotal-cf/docs-operating-pas#29]
The pane "Configure Networking - Service Mesh (Beta)" is not present in the Small Instance version. Is the same available for regular version and is that why the pane is included in the documentation ?
**Version** : TAS for VMs 2.9
**Path :** https://docs.pivotal.io/platform/application-service/2-9/operating/configure-pas.html#networking-service-mesh

**Comment by mlimonczenko** [comment]
Hello @quixoticmonk,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
