### ISSUE TITLE
PAS buckets should be distinct from OpsMan buckets

### ISSUE THREAD

**Issue by selzoc** [pivotal-cf/docs-operating-pas#31]
Hello,

We have had a couple of customer issues come up regarding configuring the PAS tile with the same buckets as the OpsMan Bosh.  This is not a supported configuration, and leads to issues.  Can we add some language in pas-file-storage.html when talking about the buckets that they should be distinct from the ones that are used for OpsMan?

**Comment by mlimonczenko** [comment]
Hello @selzoc,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
