### ISSUE TITLE
Wrong guide on how to update NSX-T loadbalancer

### ISSUE THREAD

**Issue by mhoshi-vm** [pivotal-cf/docs-operating-pas#33]
The following guide is wrong.

https://github.com/pivotal-cf/docs-operating-pas/blob/2.9/vsphere-nsx-t.html.md.erb#L300-L306

This will make configure make the **BOSH Server** the members of the loadbalancer for *system.YOUR_DOMAIN.com and *system.YOUR_DOMAIN.com which makes no sense.
Instead the resource config should be configured against the TAS for VMs tile, not the bosh tile.

**Comment by mhoshi-vm** [comment]
Updating the doc to reference here is more accurate

https://docs.pivotal.io/platform/application-service/2-9/operating/configure-lb.html

**Comment by mlimonczenko** [comment]
Hello @mhoshi-vm,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
