### ISSUE TITLE
Broken link for opsman config topic for your iaas

### ISSUE THREAD

**Issue by randomtask1155** [pivotal-cf/docs-operating-pas#4]
https://github.com/pivotal-cf/docs-operating-pas/blob/05645cf3c23595451c441fcebbca4ac4a034368f/configure-pas.html.md.erb#L13

**Comment by ljarzynski** [comment]
Hi @randomtask1155 , thank you for pointing this out. 
I just pushed a fix that should make it's way to production soon.
