### ISSUE TITLE
Clean up vSphere requirements

### ISSUE THREAD

**Issue by zmb3** [pivotal-cf/docs-operating-pas#47]
On the [_TAS for VMs on vSphere Requirements_](https://docs.pivotal.io/application-service/2-9/operating/pas-vsphere-requirements.html) page there are several things that could be improved:

- Under _Minimum Resource Requirements_ we say 2 public IPs (one for TAS and one for Ops Manager). Is a public IP for Ops Manager really a *minimum* requirement?
- There's an asymmetry between the TAS and small footprint sections. Under small footprint we recommend a specific number of hosts and resource pools, but don't offer similar recommendations for the full TAS deployment.
- The verbiage under _Instance Number and Scaling Requirements_ is confusing, as it speaks to running a "highly available configuration of Ops Manager"; there really isn't such a thing as a highly available configuration of Ops Manager - it's a single VM. I think this should probably say a "highly available configuration of TAS."

**Comment by mlimonczenko** [comment]
Hello @zmb3,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
