### ISSUE TITLE
Include documentation about removing an IDP

### ISSUE THREAD

**Issue by rcpnair** [pivotal-cf/docs-operating-pas#59]
Once a SAML IDP is configured, it's always displayed in the login page. As per the documentation , "You must manually disable a SAML IDP created by TAS for VMs when you no longer require it.". However there are no details about how to perform this operation. Could you please include step by step procedure to remove an existing SAML IDP?

**Comment by mlimonczenko** [comment]
Hello @rcpnair,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
