### ISSUE TITLE
Clarification needed on /pivotal-cf/docs-operating-pas/blob/2.10/configuring.html.md.erb

### ISSUE THREAD

**Issue by jak0lantash** [pivotal-cf/docs-operating-pas#62]
Hi,
On page https://docs.pivotal.io/application-service/2-10/operating/configuring.html#best-practices (https://github.com/pivotal-cf/docs-operating-pas/blob/2.10/configuring.html.md.erb), the following statement is made:

> Set the max_in_flight variable high enough that the remaining component instances are not overloaded by typical use.

It seems that it should be "low enough" to avoid overload, not "high enough".
Please review and update accordingly if necessary.
Regards,

**Comment by animatedmax** [comment]
Hi @jak0lantash We've corrected the phrasing to "low enough." Thank you for bringing this to our attention.
