### ISSUE TITLE
Fix OpsMan link(/s) in TAS 2.11

### ISSUE THREAD

**Issue by ctlong** [pivotal-cf/docs-operating-pas#63]
The following OpsMan link
https://github.com/pivotal-cf/docs-operating-pas/blob/1c893dee683933223f054b2f14c8a375f3b8e2c8/configure-lb.html.md.erb#L104
is constructed as https://docs.pivotal.io/ops-manager/2-11/aws/prepare-env-manual.html in TAS 2.11. That leads to a "Page Not Found", as no OpsMan 2.11 exists (yet).

This link should presumably be corrected to point to the correct docs. In the case of TAS 2.11, I believe that's OpsMan 2.10, https://docs.pivotal.io/ops-manager/2-10/aws/prepare-env-manual.html.

It's entirely possible that there are other similar errors across TAS 2.11 in cases where the OpsMan docs are linked to. I haven't verified this though.

**Comment by ctlong** [comment]
Found another one at https://github.com/pivotal-cf/docs-operating-pas/blob/2.11/configure-pas.html.md.erb#L13

**Comment by mjgutermuth** [comment]
Thanks for pointing this out @ctlong! We have addressed this issue and the links should be working as expected now.
