### ISSUE TITLE
Free-floating (& outdated?) page

### ISSUE THREAD

**Issue by ctlong** [pivotal-cf/docs-operating-pas#64]
This [page](https://github.com/pivotal-cf/docs-operating-pas/blob/2.11/er_network.html.md.erb) appears to be free floating, and not included in the table of contents. Is that by design?

Furthermore, the page does seem somewhat dated, as [this page](https://docs.pivotal.io/application-service/2-11/concepts/cf-routing-architecture.html) describes the routing architecture in a more detailed fashion.

**Comment by animatedmax** [comment]
Hi @ctlong As you've identified, this topic is outdated and we will remove it from the documentation. Thanks for catching it.
